#!/bin/sh

export LESS_TERMCAP_so=$(tput bold; tput setb 4; tput setaf 7) # white on black
export LESS_TERMCAP_mb=$(tput bold; tput setaf 0)
export LESS_TERMCAP_md=$(tput bold; tput setaf 0)
export LESS_TERMCAP_me=$(tput sgr0)
#export LESS_TERMCAP_se=$(tput rmso, tput sgr0)
export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 0)
export LESS_TERMCAP_ue=$(tput rmul; tput sgr0)
export LESS_TERMCAP_mr=$(tput rev)
export LESS_TERMCAP_mh=$(tput dim)
export LESS_TERMCAP_ZN=$(tput ssubm)
export LESS_TERMCAP_ZV=$(tput rsubm)
export LESS_TERMCAP_ZO=$(tput ssupm)
export LESS_TERMCAP_ZW=$(tput rsupm)
export GROFF_NO_SGR=1 # For Konsole and Gnome-Terminal


# 0 black
# 1
# 2 green
# 3 yellow
# 4 blue
# 5
# 6 cyan
# 7 white
